### ISSUE TITLE
[V8 groupNotifications] `java.util.ConcurrentModificationException` when `.enqueue()` tasks quickly

### ISSUE THREAD

**Issue by FluffyDiscord** [781flyingdutchman/background_downloader#208]
**Describe the bug**
I tried to download large amount of files using the `.enqueue()`, then putting my app to suspend state by exiting it, but keeping it in the recents, but I am getting some concurrent errors. It may be issue on my side, but I am not sure.

**To Reproduce**
Enqueue bunch of single download tasks quickly quickly (~600 in 1-2s). 

**Expected behavior**
Probably should not happen.

**Logs**
```
D/TrafficStats( 9472): tagSocket(580) with statsTag=0xffffffff, statsUid=-1
W/TaskWorker( 9472): Error for taskId 4072155299: null
W/TaskWorker( 9472): java.util.ConcurrentModificationException
W/TaskWorker( 9472): 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1574)
W/TaskWorker( 9472): 	at java.util.HashMap$EntryIterator.next(HashMap.java:1607)
W/TaskWorker( 9472): 	at java.util.HashMap$EntryIterator.next(HashMap.java:1605)
W/TaskWorker( 9472): 	at com.bbflight.background_downloader.GroupNotification.getNumFinished(Notifications.kt:875)
W/TaskWorker( 9472): 	at com.bbflight.background_downloader.GroupNotification.getGroupState(Notifications.kt:127)
W/TaskWorker( 9472): 	at com.bbflight.background_downloader.GroupNotification.update(Notifications.kt:135)
W/TaskWorker( 9472): 	at com.bbflight.background_downloader.NotificationService.updateGroupNotification(Notifications.kt:397)
W/TaskWorker( 9472): 	at com.bbflight.background_downloader.NotificationService.updateNotification(Notifications.kt:315)
W/TaskWorker( 9472): 	at com.bbflight.background_downloader.TaskWorker.updateProgressAndNotify(TaskWorker.kt:677)
W/TaskWorker( 9472): 	at com.bbflight.background_downloader.TaskWorker$transferBytes$2$1.invokeSuspend(TaskWorker.kt:594)
W/TaskWorker( 9472): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/TaskWorker( 9472): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
W/TaskWorker( 9472): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
W/TaskWorker( 9472): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
W/TaskWorker( 9472): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
W/TaskWorker( 9472): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
W/TaskWorker( 9472): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
W/TaskWorker( 9472): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
I/TaskWorker( 9472): Successfully downloaded taskId 3434326241 to /storage/emulated/0/Music/Small/FnK/random/Barbwalters - FunkLord/Barbwalters - FunkLord - 03 Master.flac
I/TaskWorker( 9472): Successfully downloaded taskId 3978892216 to /storage/emulated/0/Music/Small/FnK/random/Z.E.R.O - NEO DISCO WAVE/Z.E.R.O - NEO DISCO WAVE - 04 AIのジョック.flac
I/flutter ( 9472): Warning database has been locked for 0:00:10.000000. Make sure you always use the transaction object for database operations during a transaction
I/flutter ( 9472): Warning database has been locked for 0:00:10.000000. Make sure you always use the transaction object for database operations during a transaction
I/flutter ( 9472): Warning database has been locked for 0:00:10.000000. Make sure you always use the transaction object for database operations during a transaction
```

**Code**
(shortened)
```dart
process() async {
  for(var library in selectedLibraries) {
    await for(final entry in libraryManager.getAllFiles(library.remoteId!, "")) {
      final localPath = "${library.localPath}${entry.path}";
      final localPathname = "$localPath/${entry.name}";
  
        final downloadLink = await http.getDownloadLink(
          library.remoteId!,
          "${entry.path}/${entry.name}",
        );
  
        final downloadTask = DownloadTask(
          group: "default",
          url: downloadLink,
          requiresWiFi: true,
          baseDirectory: BaseDirectory.root,
          directory: localPath,
          filename: entry.name,
        );
  
        await FileDownloader().enqueue(downloadTask);
      });
    }
  }
}
```

**Comment by 781flyingdutchman** [comment]
Thanks for helping root out issues with V8! Definitely a bug, I'll fix that in the next release. Also, if you want to enqueue this many tasks quickly you need to use a TaskQueue (see documentation) to prevent choking the main thread. That will solve your database blocked error too, I think (in your code)

**Comment by 781flyingdutchman** [comment]
Hi, can you try a fix? Change your pubspec.yaml to:
```
background_downloader:
    git:
      url: https://github.com/781flyingdutchman/background_downloader.git
      ref: dev
```

to use the 'dev' branch. I believe this should fix it, but please test with your setup and let me know. Thanks!

**Comment by FluffyDiscord** [comment]
Removing temporary `background_downloader_sql` and trying the same setup, with tracking, but without the SqlPersisted package, I no longer get that exception.

The only thing I can see is this, but everything works so far.
`W/JobService( 6190): onNetworkChanged() not implemented in androidx.work.impl.background.systemjob.SystemJobService. Must override in a subclass.`

Killing the app (swiping out in the recents) and reopening it printed bunch of info messages like this:
```
I/WM-WorkerWrapper( 7199): Work [ id=6d653555-693f-4e96-9283-cb993900ec8a, tags={ com.bbflight.background_downloader.DownloadTaskWorker, BackgroundDownloader, taskId=2332912399, group=default } ] was cancelled
I/WM-WorkerWrapper( 7199): java.util.concurrent.CancellationException: Task was cancelled.
I/WM-WorkerWrapper( 7199): 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
I/WM-WorkerWrapper( 7199): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
I/WM-WorkerWrapper( 7199): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
I/WM-WorkerWrapper( 7199): 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:317)
I/WM-WorkerWrapper( 7199): 	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
I/WM-WorkerWrapper( 7199): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
I/WM-WorkerWrapper( 7199): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
I/WM-WorkerWrapper( 7199): 	at java.lang.Thread.run(Thread.java:1012)
```
Is this expected behavior ?

**Comment by 781flyingdutchman** [comment]
Thanks. The first message (JobService) is entirely unrelated. The second is annoying (because it cannot be 'caught') but innocent/expected. 

For the sql lock issue, per above, please use a [MemoryTaskQueue](https://pub.dev/packages/background_downloader#task-queues) if you need to enqueue many tasks, to avoid choking the downloader and the UI thread. In its basic implementation it's a simple buffer that throttles the `enqueue` calls for you.

I think this solves the issue then, so I am going to push this as a new version. Thanks for your help!
