### ISSUE TITLE
Failed to build on Android,look for AndroidManifest.xml

### ISSUE THREAD

**Issue by chenxiangjun2010** [781flyingdutchman/background_downloader#266]
**Describe the bug**
Failed to build on Android side, it's looking for Error parsing AndroidManifest.xml
 
**To Reproduce**
1. change compileSdkVersion from 33 to 34
2. add permission <uses-permission android:name="android.permission.FOREGROUND_SERVICE_DATA_SYNC" />
3.  and seivice  <service
  android:name="androidx.work.impl.foreground.SystemForegroundService"
  android:foregroundServiceType="dataSync"
  tools:node="merge" />
4. flutter run 

**Expected behavior**
com.android.manifmerger.ManifestMerger2$MergeFailureException: Error parsing D:\flutter\android\app\src\main\AndroidManifest.xml

**Logs**
If possible, include logs that capture the issue:
if remove "tools:node="merge" ,it's will be continued,but causing other mistake
logs
```

**Code**
If possible, paste in the code snippet where you interact with the package:
```
Code
```

**Additional context**
Add any other context about the problem here.

**Comment by 781flyingdutchman** [comment]
There is probably more of an explanation following "Error parsing D:\flutter\android\app\src\main\AndroidManifest.xml" - can you share that? Can you also try to run the example app as-is? This has the same elements and runs fine on my side. If it runs well for you, then double check that you have gotten the entries in your manifest right, and if it doesn't run then there may be an Android Studio or VS config issue (eg gradle plugin version).

**Comment by chenxiangjun2010** [comment]
![PixPin_2024-03-14_16-19-04](https://github.com/781flyingdutchman/background_downloader/assets/26141689/8d816719-cf15-43e0-a0cb-686cecd79093)
@781flyingdutchman 
`<manifest xmlns:android="http://schemas.android.com/apk/res/android">  
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
  
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32"/>
  
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="29"/>
  <uses-permission android:name="android.permission.FLASHLIGHT"/>
    
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  
  <uses-permission android:name="android.permission.READ_PHONE_STATE" />
  <uses-permission android:name="com.android.launcher.permission.READ_SETTINGS" />
  
  <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
  
  <uses-permission android:name="android.permission.WRITE_SETTINGS" />
  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
  
  <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
  
  <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
  
  <uses-permission android:name="android.permission.BLUETOOTH" />
  <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
  
  <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
  <uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation" />
  
  <uses-permission android:name="android.permission.FOREGROUND_SERVICE_DATA_SYNC"/>
  <uses-feature android:name="android.hardware.camera" android:required="true"/>
  <application android:label="管理平台" android:name="${applicationName}" android:icon="@mipmap/ic_launcher">
    <activity android:name=".MainActivity" android:exported="true" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize">      
      <meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme" />
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
    </activity>    
    <meta-data android:name="flutterEmbedding" android:value="2"/>
    
    <service android:name="com.amap.api.location.APSService"/>
    <service android:name="androidx.work.impl.foreground.SystemForegroundService"
             android:foregroundServiceType="dataSync" 
             tool:node="replace" />
  </application>
</manifest>`
my current flutter version is 3.13.8

**Comment by chenxiangjun2010** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android">  
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
  
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32"/>
  
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="29"/>
  <uses-permission android:name="android.permission.FLASHLIGHT"/>
    
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  
  <uses-permission android:name="android.permission.READ_PHONE_STATE" />
  <uses-permission android:name="com.android.launcher.permission.READ_SETTINGS" />
  
  <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
  
  <uses-permission android:name="android.permission.WRITE_SETTINGS" />
  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
  
  <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
  
  <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
  
  <uses-permission android:name="android.permission.BLUETOOTH" />
  <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
  
  <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
  <uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation" />
  
  <uses-permission android:name="android.permission.FOREGROUND_SERVICE_DATA_SYNC"/>
  <uses-feature android:name="android.hardware.camera" android:required="true"/>
  <application android:label="管理平台" android:name="${applicationName}" android:icon="@mipmap/ic_launcher">
    <activity android:name=".MainActivity" android:exported="true" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize">      
      <meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme" />
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
    </activity>    
    <meta-data android:name="flutterEmbedding" android:value="2"/>
    
    <service android:name="com.amap.api.location.APSService"/>
    <service android:name="androidx.work.impl.foreground.SystemForegroundService"
             android:foregroundServiceType="dataSync" 
             tool:node="replace" />
  </application>
</manifest>

**Comment by chenxiangjun2010** [comment]
< manifest xmlns:android="http://schemas.android.com/apk/res/android">  
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
  
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32"/>
  
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="29"/>
  <uses-permission android:name="android.permission.FLASHLIGHT"/>
    
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  
  <uses-permission android:name="android.permission.READ_PHONE_STATE" />
  <uses-permission android:name="com.android.launcher.permission.READ_SETTINGS" />
  
  <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
  
  <uses-permission android:name="android.permission.WRITE_SETTINGS" />
  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
  
  <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
  
  <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
  
  <uses-permission android:name="android.permission.BLUETOOTH" />
  <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
  
  <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
  <uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation" />
  
  <uses-permission android:name="android.permission.FOREGROUND_SERVICE_DATA_SYNC"/>
  <uses-feature android:name="android.hardware.camera" android:required="true"/>
  <application android:label="管理平台" android:name="${applicationName}" android:icon="@mipmap/ic_launcher">
    <activity android:name=".MainActivity" android:exported="true" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize">      
      <meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme" />
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
    </activity>    
    <meta-data android:name="flutterEmbedding" android:value="2"/>
    
    <service android:name="com.amap.api.location.APSService"/>
    <service android:name="androidx.work.impl.foreground.SystemForegroundService"
             android:foregroundServiceType="dataSync" 
             tool:node="replace" />
  </application>
</manifest >

**Comment by chenxiangjun2010** [comment]
![PixPin_2024-03-14_16-58-28](https://github.com/781flyingdutchman/background_downloader/assets/26141689/2b409e95-b789-418b-9150-31ff915dce7b)
@781flyingdutchman

**Comment by chenxiangjun2010** [comment]
> There is probably more of an explanation following "Error parsing D:\flutter\android\app\src\main\AndroidManifest.xml" - can you share that? Can you also try to run the example app as-is? This has the same elements and runs fine on my side. If it runs well for you, then double check that you have gotten the entries in your manifest right, and if it doesn't run then there may be an Android Studio or VS config issue (eg gradle plugin version).
**gradle plugin version**
![PixPin_2024-03-14_16-58-28](https://github.com/781flyingdutchman/background_downloader/assets/26141689/eafcecbb-08f6-49f9-bd4e-0e82179443ce)
**mistake**
![PixPin_2024-03-14_16-19-04](https://github.com/781flyingdutchman/background_downloader/assets/26141689/0deef4f2-befd-4882-a84f-096bd898f243)
**flutter version**
3.13.8
**code**
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android">  <!--允许访问网络，必选权限-->
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
  <!--允许读设备等信息，用于问题排查-->
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32"/>
  <!--允许写入扩展存储，用于写入缓存定位数据-->
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="29"/>
  <uses-permission android:name="android.permission.FLASHLIGHT"/>
  <!-- 地图 -->  <!--允许获取网络状态，用于网络定位（无gps情况下的定位），若需网络定位功能则必选-->
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <!--允许获取设备和运营商信息，用于问题排查和网络定位（无gps情况下的定位），若需网络定位功能则必选-->
  <uses-permission android:name="android.permission.READ_PHONE_STATE" />
  <uses-permission android:name="com.android.launcher.permission.READ_SETTINGS" />
  <!--允许获取wifi网络信息，用于网络定位（无gps情况下的定位），若需网络定位功能则必选-->
  < uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
  <!--允许写设备缓存，用于问题排查-->
  <uses-permission android:name="android.permission.WRITE_SETTINGS" />
  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
  <!--允许获取wifi状态改变，用于网络定位（无gps情况下的定位），若需网络定位功能则必选-->
  <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
  <!--后台获取位置信息，若需后台定位则必选-->
  <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
  <!-- 蓝⽛权限 -->
  <uses-permission android:name="android.permission.BLUETOOTH" />
  <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
  <!-- android 5以上 android 12以下，蓝⽛搜索需要位置权限 -->  <!--允许获取精确位置，精准定位必选-->
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
  <!--android 12 需要申请蓝⽛搜索权限、连接权限 ⽆需申请位置权限 -->
  <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
  <uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation" />
  <!-- 下载 -->
  <uses-permission android:name="android.permission.FOREGROUND_SERVICE_DATA_SYNC"/>
  <uses-feature android:name="android.hardware.camera" android:required="true"/>
  <application android:label="管理平台" android:name="${applicationName}" android:icon="@mipmap/ic_launcher">
    <activity android:name=".MainActivity" android:exported="true" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize">      <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
      <meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme" />
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
    </activity>    <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
    <meta-data android:name="flutterEmbedding" android:value="2"/>
    <!-- 配置定位Service -->
    <service android:name="com.amap.api.location.APSService"/>
    <service android:name="androidx.work.impl.foreground.SystemForegroundService"
             android:foregroundServiceType="dataSync" 
             tool:node="replace" />
  </application>
</manifest>

**Comment by chenxiangjun2010** [comment]
i change kotlin_version from kotlin_version to 1.9.0,it's alse cause same mistake, Error parsing AndroidManifest.xml,i don't konw how to get more info
@781flyingdutchman

**Comment by 781flyingdutchman** [comment]
(please paste errors as text, not as images)
The error indicates you are using a Gradle Plugin that is not compatible with Android 34, yet this foreground permission was introduced in Android 34, so I woudl start upgrading your gradle plugin. Then I would make sure you can compile the example app, targeting Android 34, and only if that works look further into your manifest file to isolate where the parsing error occurs.

**Comment by chenxiangjun2010** [comment]
can u git clone https://github.com/chenxiangjun2010/flutterTestDemo.git？this is my dev @781flyingdutchman

**Comment by chenxiangjun2010** [comment]
1.change distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip  to distributionUrl=https\://services.gradle.org/distributions/gradle-8.2.1-all.zip
2.change classpath 'com.android.tools.build:gradle:7.3.0' to classpath 'com.android.tools.build:gradle:7.4.0'
3. to upgrading mygradle plugin

**Logs**
```
Task 'compileDebug' is ambiguous in root project 'android' and its subprojects. Candidates are: 'compileDebugAidl', 'compileDebugAndroidTestAidl', 'compileDebugAndroidTestJavaWithJavac', 'compileDebugAndroidTestKotlin', 'compileDebugAndroidTestRenderscript', 'compileDebugAndroidTestShaders', 'compileDebugAndroidTestSources', 'compileDebugArtProfile', 'compileDebugJavaWithJavac', 'compileDebugKotlin', 'compileDebugLibraryResources', 'compileDebugRenderscript', 'compileDebugShaders', 'compileDebugSources', 'compileDebugUnitTestJavaWithJavac', 'compileDebugUnitTestKotlin', 'compileDebugUnitTestSources'.

* Try:
> Run gradlew tasks to get a list of available tasks.
> For more on name expansion, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:name_abbreviation in the Gradle documentation.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.execution.TaskSelectionException: Task 'compileDebug' is ambiguous in root project 'android' and its subprojects. Candidates are: 'compileDebugAidl', 'compileDebugAndroidTestAidl', 'compileDebugAndroidTestJavaWithJavac', 'compileDebugAndroidTestKotlin', 'compileDebugAndroidTestRenderscript', 'compileDebugAndroidTestShaders', 'compileDebugAndroidTestSources', 'compileDebugArtProfile', 'compileDebugJavaWithJavac', 'compileDebugKotlin', 'compileDebugLibraryResources', 'compileDebugRenderscript', 'compileDebugShaders', 'compileDebugSources', 'compileDebugUnitTestJavaWithJavac', 'compileDebugUnitTestKotlin', 'compileDebugUnitTestSources'.
        at org.gradle.execution.DefaultTaskSelector.getSelection(DefaultTaskSelector.java:86)
        at org.gradle.execution.selection.DefaultBuildTaskSelector.resolveTaskName(DefaultBuildTaskSelector.java:98)
        at org.gradle.execution.commandline.CommandLineTaskParser.parseTasks(CommandLineTaskParser.java:49)
        at org.gradle.execution.TaskNameResolvingBuildTaskScheduler.scheduleRequestedTasks(TaskNameResolvingBuildTaskScheduler.java:51)

```

**Comment by 781flyingdutchman** [comment]
Hi, I'm sorry but I have no idea what `compileDebug` is. I did notice in your repo the app/build.gradle says targetSdkVersion 33 (and not 34). I am no expert on configuring the Android build environment (I find it rather complicated) so I am not sure I can help you.

**Comment by chenxiangjun2010** [comment]
Which version supports 33，now is 8.3.0 @781flyingdutchman

**Comment by chenxiangjun2010** [comment]
I used version 8.0.3 to fix my problem, but I wonder why I can't use the latest version

**Comment by 781flyingdutchman** [comment]
Great! I think the Flutter environment always lags a little.
