### ISSUE TITLE
File or Image Uploads in Offline Mode, Success upon Reconnection but responseBody is null

### ISSUE THREAD

**Issue by YqngQB** [781flyingdutchman/background_downloader#285]
### Problem Description
Attempting to upload files or images while offline, then switching the app to the background. Upon network reconnection and automatic re-upload success, re-entering the app triggers the `taskStatusCallback` callback function again, but this time the `responseBody` is null.

### Steps to Reproduce
1. Attempt to upload a file or image in the app and disconnect from the network.
2. Switch the app to the background.
3. Reconnect to the network and wait for the file to automatically re-upload.
4. Re-enter the app.

### Expected Behavior
After network reconnection, the file should automatically re-upload successfully, and upon re-entering the app, the `taskStatusCallback` callback function should return a valid `responseBody`.

### Actual Behavior
After network reconnection, the file automatically re-uploads successfully, but upon re-entering the app, the `taskStatusCallback` callback function returns a `responseBody` that is null.

### Terminal Logs
I/TaskWorker( 6762): Starting task with taskId b6fe8ee3-3e83-4992-ac20-0b9fdb5c99221712593883377
...
I/TaskWorker( 6762): Successfully uploaded taskId b6fe8ee3-3e83-4992-ac20-0b9fdb5c99221712593883377 from /data/user/0/com.example.qst_im/cache/4bbafc77-e8cd-48c5-87c7-a8859f79bd62//1000017188.jpg
...
I/WM-WorkerWrapper( 6762): Worker result SUCCESS for Work [ id=d5f68875-cc27-4750-ae67-fbf3f80dcd0e, tags={ com.bbflight.background_downloader.UploadTaskWorker, BackgroundDownloader, taskId=b6fe8ee3-3e83-4992-ac20-0b9fdb5c99221712593883377, group=default } ]

### Environment Information
- Version: background_downloader: ^8.4.2
![Snipaste_2024-04-09_00-42-27](https://github.com/781flyingdutchman/background_downloader/assets/68342537/b942e551-7c77-4a3b-8b88-81721fad9031)

**Comment by YqngQB** [comment]
Here is the reproduction example I've prepared. I hope this helps you better understand the issue. 
```
import 'dart:async';
import 'dart:convert';

import 'package:background_downloader/background_downloader.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:logging/logging.dart';

void main() {
  Logger.root.onRecord.listen((LogRecord rec) {
    debugPrint(
        '${rec.loggerName}>${rec.level.name}: ${rec.time}: ${rec.message}');
  });

  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final log = Logger('ExampleApp');

  bool downloadWithError = false;
  TaskStatus? downloadTaskStatus;
  DownloadTask? backgroundDownloadTask;
  StreamController<TaskProgressUpdate> progressUpdateStream =
      StreamController();

  bool loadAndOpenInProgress = false;
  bool loadABunchInProgress = false;

  void fileDownloaderConfig() async {
    FileDownloader().configure(globalConfig: [
      (Config.requestTimeout, const Duration(seconds: 100)),
    ], androidConfig: [
      (Config.useCacheDir, Config.whenAble),
    ], iOSConfig: [
      (Config.localize, {'Cancel': 'StopIt'}),
    ]).then((result) => debugPrint('Configuration result = $result'));

    // Registering a callback and configure notifications
    FileDownloader()
        .registerCallbacks(
            taskNotificationTapCallback: myNotificationTapCallback,
            taskStatusCallback: myTaskStatusCallback)
        .configureNotificationForGroup(FileDownloader.defaultGroup,
            // For the main download button
            // which uses 'enqueue' and a default group
            running: const TaskNotification('Download {filename}',
                'File: {filename} - {progress} - speed {networkSpeed} and {timeRemaining} remaining'),
            complete: const TaskNotification(
                '{displayName} download {filename}', 'Download complete'),
            error: const TaskNotification(
                'Download {filename}', 'Download failed'),
            paused: const TaskNotification(
                'Download {filename}', 'Paused with metadata {metadata}'),
            progressBar: true)
        .configureNotificationForGroup('bunch',
            running: const TaskNotification(
                '{numFinished} out of {numTotal}', 'Progress = {progress}'),
            complete:
                const TaskNotification("Done!", "Loaded {numTotal} files"),
            error: const TaskNotification(
                'Error', '{numFailed}/{numTotal} failed'),
            progressBar: false,
            groupNotificationId: 'notGroup')
        .configureNotification(
            // for the 'Download & Open' dog picture
            // which uses 'download' which is not the .defaultGroup
            // but the .await group so won't use the above config
            complete: const TaskNotification(
                'Download {filename}', 'Download complete'),
            tapOpensFile: true); // dog can also open directly from tap
    await FileDownloader().trackTasks();
    await FileDownloader().resumeFromBackground();
  }

  @override
  void initState() {
    super.initState();
    fileDownloaderConfig();
  }

  /// Process the user tapping on a notification by printing a message
  void myNotificationTapCallback(Task task, NotificationType notificationType) {
    debugPrint(
        'Tapped notification $notificationType for taskId ${task.taskId}');
  }

  Future<void> myTaskStatusCallback(TaskStatusUpdate update) async {
    if (update.status == TaskStatus.complete) {
      Map<String, dynamic> responseMap = jsonDecode(update.responseBody ?? '');
      print('responseMap: $responseMap');
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        useMaterial3: true,

        // Define the default brightness and colors.
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.purple,
          brightness: Brightness.light,
        ),
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('background_downloader example app'),
        ),
        body: Center(
            child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Center(
                  child: ElevatedButton(
                onPressed: processButtonPress,
                child: Text(
                  'UploadTask Demo',
                ),
              )),
            ],
          ),
        )),
      ),
    );
  }

  Future<void> processButtonPress() async {
    XFile? image = await ImagePicker().pickImage(source: ImageSource.gallery);
    if (image == null) {
      return;
    }
    String directory =
        image.path.substring(0, image.path.length - image.name.length);
    UploadTask uploadTask = UploadTask(
      group: 'default',
      url: 'http://218.77.107.37:48999/upload/chat',

      /// 文件上传的目标URL。
      filename: image.name,

      /// 上传的文件名。
      baseDirectory: BaseDirectory.root,

      /// 文件存储的基本目录。
      directory: directory,
      fileField: 'file',
      retries: 3,
      priority: 2,

      /// 任务的优先级
      updates: Updates.statusAndProgress,
      metaData: 'upload',
    );
    FileDownloader().enqueue(uploadTask).then((value) {
      print('The file upload task has been added to the queue');
    });
  }
}
```
**Logs**
If possible, include logs that capture the issue:
```
I/HandWritingStubImpl( 3889): refreshLastKeyboardType: 1
I/HandWritingStubImpl( 3889): getCurrentKeyboardType: 1
D/ContentCatcher_injector( 3889): Interceptor : notifyActivityPause: com.example.qst_im@com.example.qst_im.MainActivity@186914496
D/ContentCatcher_catcher( 3889): CatcherHolder : mCatcherList size: 3
E/ActivityThread( 3889):  fail in deliverResultsIfNeeded java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
E/ActivityThread( 3889):  fail in deliverResultsIfNeeded java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
D/ContentCatcher_injector( 3889): Interceptor : notifyActivityResume: com.example.qst_im@com.example.qst_im.MainActivity@186914496
D/ContentCatcher_catcher( 3889): CatcherHolder : mCatcherList size: 3
D/ContentCatcher_TaplusBlackListHelper( 3889):  mActivities : [com.example.qst_im.MainActivity] Blacklist json : [com.android.contacts, com.android.fileexplorer, com.android.settings, com.android.deskclock, com.android.soundrecorder, com.miui.calculator, com.miui.voiceassist, com.kiloo.subwaysurf, com.miui.player, com.sdu.didi.psnger, com.tencent.lolm, com.tencent.tmgp.sgame, com.xiaomi.smarthome, com.miui.personalassistant, com.milink.service]
I/ContentCatcher_TaplusBlackListHelper( 3889):  blackList size: 15 package is com.example.qst_im isInTaplusWhiteList: true
I/HandWritingStubImpl( 3889): refreshLastKeyboardType: 1
I/HandWritingStubImpl( 3889): getCurrentKeyboardType: 1
I/BackgroundDownloader( 3889): Enqueuing task with id 190098072
I/flutter ( 3889): The file upload task has been added to the queue
I/MiuiKeyEventUtil( 3889): Can't match right device
D/ContentCatcher_injector( 3889): Interceptor : rootView onBackPressed: DecorView@fdff62a[MainActivity]
D/ContentCatcher_injector( 3889): Interceptor : MSG_EVENT_: 101
I/MiuiKeyEventUtil( 3889): Can't match right device
D/ContentCatcher_injector( 3889): Interceptor : notifyActivityPause: com.example.qst_im@com.example.qst_im.MainActivity@186914496
D/ContentCatcher_catcher( 3889): CatcherHolder : mCatcherList size: 3
W/.example.qst_im( 3889): Cleared Reference was only reachable from finalizer (only reported once)
I/.example.qst_im( 3889): This is non sticky GC, maxfree is 33554432 minfree is 8388608
D/ContentCatcher_injector( 3889): Interceptor : notifyActivityStop: com.example.qst_im@com.example.qst_im.MainActivity@186914496
D/ContentCatcher_catcher( 3889): CatcherHolder : mCatcherList size: 3
D/ContentCatcher_injector( 3889): Interceptor : notifyActivityDestroy: com.example.qst_im@com.example.qst_im.MainActivity@186914496
D/ContentCatcher_catcher( 3889): CatcherHolder : mCatcherList size: 3
W/MessageMonitor( 3889): PerfMonitor: Slow Operation: Activity com.example.qst_im/.MainActivity onDestroy took 145ms
W/WindowOnBackDispatcher( 3889): sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda22@1ae8380
I/TaskWorker( 3889): Starting task with taskId 190098072
I/TaskWorker( 3889): Could not post statusUpdate to background channel
D/TaskWorker( 3889): Could not post status update -> storing locally
I/TaskWorker( 3889): Could not post progressUpdate to background channel
D/TaskWorker( 3889): Could not post progress update -> storing locally
D/TrafficStats( 3889): tagSocket(82) with statsTag=0xffffffff, statsUid=-1
I/TaskWorker( 3889): Could not post progressUpdate to background channel
D/TaskWorker( 3889): Could not post progress update -> storing locally
I/TaskWorker( 3889): Successfully uploaded taskId 190098072 from /data/user/0/com.example.qst_im/cache/221ba010-8ee9-4d53-834f-6f9edfb819ce//1000017188.jpg
I/TaskWorker( 3889): Could not post progressUpdate to background channel
D/TaskWorker( 3889): Could not post progress update -> storing locally
I/TaskWorker( 3889): Could not post statusUpdate to background channel
D/TaskWorker( 3889): Could not post status update -> storing locally
I/WM-WorkerWrapper( 3889): Worker result SUCCESS for Work [ id=68375bfe-1420-419a-ad19-e4c2e7adbb2f, tags={ com.bbflight.background_downloader.UploadTaskWorker, BackgroundDownloader, taskId=190098072, group=default } ]
D/AppScoutStateMachine( 3889): 3889-ScoutStateMachinecreated
D/ContentCatcher_injector( 3889): Interceptor : Init Interceptor for Activity com.example.qst_im.MainActivity@a90d065
D/ViewContentFactory( 3889): initViewContentFetcherClass
I/ContentCatcher( 3889): ViewContentFetcher : ViewContentFetcher
D/ViewContentFactory( 3889): createInterceptor took 1ms
D/ContentCatcher_injector( 3889): Interceptor : notifyActivityCreate: com.example.qst_im@com.example.qst_im.MainActivity@177262693
I/ContentCatcher( 3889): Interceptor : Catcher list invalid for com.example.qst_im@com.example.qst_im.MainActivity@177262693
I/ContentCatcher( 3889): Interceptor : Get featureInfo from config image_pick_mode
D/ContentCatcher_config( 3889): Interceptor : featureInfo  MATCH for com.example.qst_im@com.example.qst_im.MainActivity@177262693
D/ContentCatcher_config( 3889): Interceptor : WebViewCatcher in featureInfo
D/ContentCatcher_catcher( 3889): CatcherFactory : createCatcher WebViewCatcher
D/ContentCatcher_catcher( 3889): CatcherImpl : parseFeatureInfoParams
D/ContentCatcher_config( 3889): Interceptor : ImageViewCatcher in featureInfo
D/ContentCatcher_catcher( 3889): CatcherFactory : createCatcher ImageViewCatcher
D/ContentCatcher_catcher( 3889): CatcherImpl : parseFeatureInfoParams
I/ContentCatcher( 3889): Interceptor : Get featureInfo from config pick_mode
D/ContentCatcher_config( 3889): Interceptor : featureInfo  MATCH for com.example.qst_im@com.example.qst_im.MainActivity@177262693
D/ContentCatcher_config( 3889): Interceptor : WebViewCatcher in featureInfo
D/ContentCatcher_catcher( 3889): CatcherImpl : parseFeatureInfoParams
D/ContentCatcher_config( 3889): Interceptor : NativeTextCatcher in featureInfo
D/ContentCatcher_catcher( 3889): CatcherFactory : createCatcher NativeTextCatcher
D/ContentCatcher_catcher( 3889): CatcherImpl : parseFeatureInfoParams
D/ContentCatcher_catcher( 3889): CatcherHolder : mCatcherList size: 3
D/Interceptor( 3889): needCancelLongClick com.example.qst_im@com.example.qst_im.MainActivity@177262693 enable:true
D/ContentCatcher_catcher( 3889): CatcherHolder : mCatcherList size: 3
D/DecorView[]( 3889): getWindowModeFromSystem  windowmode is 1
D/ContentCatcher_injector( 3889): Interceptor : notifyActivityStart: com.example.qst_im@com.example.qst_im.MainActivity@177262693
D/ContentCatcher_catcher( 3889): CatcherHolder : mCatcherList size: 3
D/ContentCatcher_injector( 3889): Interceptor : notifyActivityResume: com.example.qst_im@com.example.qst_im.MainActivity@177262693
D/ContentCatcher_catcher( 3889): CatcherHolder : mCatcherList size: 3
I/ContentCatcher_TaplusBlackListHelper( 3889):  mActivities isEmpty
D/ContentCatcher_TaplusBlackListHelper( 3889):  mActivities : [com.example.qst_im.MainActivity] Blacklist json : [com.android.contacts, com.android.fileexplorer, com.android.settings, com.android.deskclock, com.android.soundrecorder, com.miui.calculator, com.miui.voiceassist, com.kiloo.subwaysurf, com.miui.player, com.sdu.didi.psnger, com.tencent.lolm, com.tencent.tmgp.sgame, com.xiaomi.smarthome, com.miui.personalassistant, com.milink.service]
I/ContentCatcher_TaplusBlackListHelper( 3889):  blackList size: 15 package is com.example.qst_im isInTaplusWhiteList: true
E/OpenGLRenderer( 3889): Unable to match the desired swap behavior.
D/VRI[MainActivity]( 3889): vri.reportNextDraw android.view.ViewRootImpl.performTraversals:4293 android.view.ViewRootImpl.doTraversal:2933 android.view.ViewRootImpl$TraversalRunnable.run:10224 android.view.Choreographer$CallbackRecord.run:1626 android.view.Choreographer$CallbackRecord.run:1635 
D/SurfaceView( 3889): UPDATE null, mIsCastMode = false
D/SurfaceView( 3889): UPDATE Surface(name=SurfaceView[com.example.qst_im/com.example.qst_im.MainActivity]#193567)/@0xf5bfe1c, mIsProjectionMode = false
D/BackgroundDownloader( 3889): Setting preference key com.bbflight.background_downloader.config.requestTimeout to 100
D/BackgroundDownloader( 3889): Setting preference key com.bbflight.background_downloader.config.useCacheDir to -2
D/VRI[MainActivity]( 3889): vri.reportNextDraw android.view.ViewRootImpl.performTraversals:4293 android.view.ViewRootImpl.doTraversal:2933 android.view.ViewRootImpl$TraversalRunnable.run:10224 android.view.Choreographer$CallbackRecord.run:1626 android.view.Choreographer$CallbackRecord.run:1635 
I/flutter ( 3889): Configuration result = [(requestTimeout, ), (useCacheDir, )]
D/VRI[MainActivity]( 3889): vri.Setup new sync=wmsSync-VRI[MainActivity]#19
D/OpenGLRenderer( 3889): makeCurrent grContext:0xb400006f134afb80 reset mTextureAvailable
D/VRI[MainActivity]( 3889): vri.reportDrawFinished
I/HandWritingStubImpl( 3889): refreshLastKeyboardType: 1
I/HandWritingStubImpl( 3889): getCurrentKeyboardType: 1
E/flutter ( 3889): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected end of input (at character 1)
E/flutter ( 3889): 
E/flutter ( 3889): ^
E/flutter ( 3889): 
E/flutter ( 3889): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1376:5)
E/flutter ( 3889): #1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:494:7)
E/flutter ( 3889): #2      _parseJson (dart:convert-patch/convert_patch.dart:36:10)
E/flutter ( 3889): #3      JsonDecoder.convert (dart:convert/json.dart:610:36)
E/flutter ( 3889): #4      JsonCodec.decode (dart:convert/json.dart:216:41)
E/flutter ( 3889): #5      jsonDecode (dart:convert/json.dart:155:10)
E/flutter ( 3889): #6      _MyAppState.myTaskStatusCallback (package:demo/main.dart:98:42)
E/flutter ( 3889): #7      BaseDownloader._emitStatusUpdate (package:background_downloader/src/base_downloader.dart:750:29)
E/flutter ( 3889): #8      BaseDownloader.processStatusUpdate (package:background_downloader/src/base_downloader.dart:686:7)
E/flutter ( 3889): #9      BaseDownloader.retrieveLocallyStoredData (package:background_downloader/src/base_downloader.dart:193:9)
E/flutter ( 3889): <asynchronous suspension>
E/flutter ( 3889): #10     _MyAppState.fileDownloaderConfig (package:demo/main.dart:80:5)
E/flutter ( 3889): <asynchronous suspension>
E/flutter ( 3889): 
I/flutter ( 3889): BaseDownloader>WARNING: 2024-04-09 02:20:25.429878: Requested progress updates for task 190098072 in group default but no TaskProgressCallback was registered, and there is no listener to the updates stream
```

**Comment by YqngQB** [comment]
> Thanks for raising this. Can you also post the logs of the moment you disconnect and then reconnect? I need to understand which 'retry' flow is happening when this happens. Thanks.

I have been troubled by this issue for a long time, and I am very grateful for your help. Below, I have provided an example, hoping it will be helpful to you!

**Comment by 781flyingdutchman** [comment]
Very helpful. I know where the problem is, give me a couple of days to see if I can fix this.

**Comment by 781flyingdutchman** [comment]
Can you try the fix? Update your pubspec.yaml entry to:
```
background_downloader:
    git:
      url: https://github.com/781flyingdutchman/background_downloader.git
      ref: statusUpdate
```

and let me know if this addresses the issue

**Comment by YqngQB** [comment]
Sure, I will try the fix later and provide you with feedback promptly. Thank you for the suggestion!

**Comment by YqngQB** [comment]
> Can you try the fix? Update your pubspec.yaml entry to:
> 
> ```
> background_downloader:
>     git:
>       url: https://github.com/781flyingdutchman/background_downloader.git
>       ref: statusUpdate
> ```
> 
> and let me know if this addresses the issue

Thank you for the suggestion. I have updated the pubspec.yaml entry as you recommended, and the issue has been resolved. I appreciate your help!

**Comment by YqngQB** [comment]
I'm encountering an error while attempting to update to background_downloader ^8.4.3. The error message reads as follows:
