### ISSUE TITLE
Could not listen stream

### ISSUE THREAD

**Issue by 1041harpreet** [781flyingdutchman/background_downloader#297]
**Describe the bug**
I have one screen where i am showing all the videos which are currently downloading. i am using stream controller and when i try to listen stream, i got error Bad state: Stream has already been listened to.

**To Reproduce**
1. create stream builder to listen  stream
2. click on download

**Expected behavior**
I want to get all videos with progress which are currently downloading

**Logs**
If possible, include logs that capture the issue:
```
logs
```

**Code**
If possible, paste in the code snippet where you interact with the package:
```
import 'dart:async';
import 'dart:convert';

import 'package:background_downloader/background_downloader.dart';
import 'package:flutter/cupertino.dart';
import 'package:logging/logging.dart';

import 'all_videos_screen.dart';

enum ButtonState {
  download,
  cancel,
  pause,
  reset,
  resume,
  done,
  running,
  failed,
  notFound,
  loading
}

class DownloadManager extends ChangeNotifier {

  final buttonTexts = ['Download', 'Cancel', 'Pause', 'Resume', 'Reset'];


  StreamController<TaskProgressUpdate> progressUpdateStream =
      StreamController();

  // Constructor
  configure() {
    FileDownloader().configure(globalConfig: [
      (
        Config.requestTimeout,
        const Duration(seconds: 100),
      ),
    ], androidConfig: [
      (Config.useCacheDir, Config.whenAble),
    ], iOSConfig: [
      (Config.localize, {'Cancel': 'StopIt'}),
    ]).then((result) => debugPrint('Configuration result = $result'));

    // Registering a callback and configure notifications
    FileDownloader()
        .registerCallbacks(
          taskNotificationTapCallback: myNotificationTapCallback,
        )
        .configureNotificationForGroup(FileDownloader.defaultGroup,
            running: const TaskNotification('Download {filename}',
                'File: {filename} - {progress} - speed {networkSpeed} and {timeRemaining} remaining'),
            complete: const TaskNotification(
                '{displayName} download {filename}', 'Download complete'),
            error: const TaskNotification(
                'Download {filename}', 'Download failed'),
            paused: const TaskNotification(
                'Download {filename}', 'Paused with metadata {metadata}'),
            progressBar: true)
        .configureNotificationForGroup('bunch',
            running: const TaskNotification(
                '{numFinished} out of {numTotal}', 'Progress = {progress}'),
            complete:
                const TaskNotification("Done!", "Loaded {numTotal} files"),
            error: const TaskNotification(
                'Error', '{numFailed}/{numTotal} failed'),
            progressBar: false,
            groupNotificationId: 'notGroup')
        .configureNotification(
            complete: const TaskNotification(
                'Download {filename}', 'Download complete'),
            tapOpensFile: true);

    // Listen to updates and process
    FileDownloader().updates.listen((update) {
      switch (update) {
        case TaskStatusUpdate():
          print(update.status);
          var data = update.task.metaData;
          var decodedData = json.decode(data);
          if (decodedData is Map<String, dynamic>) {
            var videoId = decodedData['id'];
          updateStatus(videoId,update);
          }
          break;

        case TaskProgressUpdate():
          var data = update.task.metaData;
          var decodedData = json.decode(data);
          if (decodedData is Map<String, dynamic>) {
            var videoId = decodedData['id'];
            var foundVideo =
                videoList.firstWhere((video) => video.id == videoId);
            foundVideo.progress = update.progress;
            if (update.progress == 1) {
              foundVideo.buttonState = ButtonState.done;
            }
            notifyListeners();
          }
          progressUpdateStream.add(update); // Pass on to widget for indicator
          break;
      }
    });
  }

  void updateStatus(videoId,update){
    try{
      var foundVideo =
      videoList.firstWhere((video) => video.id == videoId);
      foundVideo.buttonState = getState(update);
      print('update the status ${foundVideo.buttonState}');
      notifyListeners();
    }catch(e){
      print(e);
    }
  }

  ButtonState getState(TaskStatusUpdate update) {
    if (update.status == TaskStatus.enqueued ||
        update.status == TaskStatus.waitingToRetry) {
      return ButtonState.loading;
    } else if (update.status == TaskStatus.running) {
      return ButtonState.running;
    } else if (update.status == TaskStatus.complete) {
      return ButtonState.done;
    } else if (update.status == TaskStatus.canceled) {
      return ButtonState.cancel;
    } else if (update.status == TaskStatus.paused) {
      return ButtonState.pause;
    } else if (update.status == TaskStatus.failed) {
      return ButtonState.failed;
    } else if (update.status == TaskStatus.notFound) {
      return ButtonState.notFound;
    }
    return ButtonState.download;
  }

  void myNotificationTapCallback(Task task, NotificationType notificationType) {
    debugPrint(
        'Tapped notification $notificationType for taskId ${task.taskId}');
  }

  // Method to handle button press
  Future<void> processButtonPress(ButtonState state, Video video) async {
    switch (state) {
      case ButtonState.download:
        // start download
        await getPermission(PermissionType.notifications);
        DownloadTask task = DownloadTask(
            taskId: video.id.toString(),
            url: video.url,
            filename: '${video.title}.mp4',
            directory: 'Audio',
            baseDirectory: BaseDirectory.applicationDocuments,
            updates: Updates.statusAndProgress,
            retries: 3,
            allowPause: true,
            metaData: json.encode(video),
            displayName: video.title);
        video.downloadTask = task;
        await FileDownloader().enqueue(task);
        break;
      case ButtonState.cancel:
        // cancel download
        await FileDownloader().cancelTasksWithIds([video.id.toString()]);

        break;
      case ButtonState.reset:
        // downloadTaskStatus = null;
        // buttonState = ButtonState.download;
        break;
      case ButtonState.pause:
        print('pausing download');
        if (video.downloadTask != null) {
          await FileDownloader().pause(video.downloadTask!);
        }
        break;
      case ButtonState.resume:
        if (video.downloadTask != null) {
          bool isPaused=await FileDownloader().resume(video.downloadTask!);
          print(isPaused);
        }
        break;
      case ButtonState.done:
      // TODO: Handle this case.
      case ButtonState.running:
      // TODO: Handle this case.
      case ButtonState.failed:
        // TODO: Handle this case.
      case ButtonState.notFound:
        // TODO: Handle this case.
      case ButtonState.loading:
        // TODO: Handle this case.
    }
    notifyListeners();
  }

  // Method to handle permission requests
  Future<void> getPermission(PermissionType permissionType) async {
    var status = await FileDownloader().permissions.status(permissionType);
    if (status != PermissionStatus.granted) {
      if (await FileDownloader()
          .permissions
          .shouldShowRationale(permissionType)) {
        debugPrint('Showing some rationale');
      }
      status = await FileDownloader().permissions.request(permissionType);
      debugPrint('Permission for $permissionType was $status');
    }
  }

  // Dispose method to clean up resources
  void dispose() {
    progressUpdateStream.close();
    super.dispose();
  }
}
 i am listening this stream as  
StreamBuilder<TaskProgressUpdate>(
                  stream: Provider.of<DownloadManager>(context)
                      .progressUpdateStream
                      .stream,
                  builder: (context, snapshot) {
                    if (snapshot.connectionState == ConnectionState.waiting) {
                      return const Center(
                        child: CircularProgressIndicator(),
                      );
                    } else if (snapshot.hasError) {
                      return Center(
                        child: Text('Error: ${snapshot.error}'),
                      );
                    } else if (!snapshot.hasData) {
                      return const Center(
                        child: Text('No data available'),
                      );
                    }
                    return const Text('data');
                  })
```

**Additional context**

**Comment by 781flyingdutchman** [comment]
Hi, see https://github.com/781flyingdutchman/background_downloader/discussions/146#discussioncomment-8537492 for how to properly listen to the stream.

**Comment by 1041harpreet** [comment]
i created singleton like this
 `class DownloadManager extends ChangeNotifier {
  static final DownloadManager _instance = DownloadManager._internal();

  factory DownloadManager() {
    return _instance;
  }

  DownloadManager._internal();

  static DownloadManager get instance => _instance;`

how do we can show filename,progress of downloading file using this singleton object. rest of the code  is same

**Comment by 1041harpreet** [comment]
Thank you for the quick response. I managed to do listening of steam. But why my task got failed when I go to background and secondly when I try to use pause it cancel the task then it again starting to download. Why I am getting this issue

**Comment by 781flyingdutchman** [comment]
Cancellation on pause likely means that your server does not support partial downloads. Not sure what you mean with "go to background" as that's not something you as a user can do - it's the OS that determines if your app gets suspended.

**Comment by 1041harpreet** [comment]
what do you mean by " your server does not support partial downloads" , i am trying to download video from url, is there any specific related to url also? btw i am trying to download video of 1gb , this is url "https://testfile.org/files-1GB-8k-mp4" i tried with your example code, pausing of task does not pausing , it shows this in console 

`Work [ id=a14f59a8-3b43-46e5-908a-493a1683dded, tags={ com.bbflight.background_downloader.DownloadTaskWorker, BackgroundDownloader, taskId=810408991, group=default } ] was cancelled
I/WM-WorkerWrapper(20832): java.util.concurrent.CancellationException: Task was cancelled.
I/WM-WorkerWrapper(20832): 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1183)
I/WM-WorkerWrapper(20832): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:513)`
