### ISSUE TITLE
Upload tasks get randomly restarted on a slow Android device

### ISSUE THREAD

**Issue by Ansis100** [781flyingdutchman/background_downloader#344]
When testing on a slow Android 12 device and enqueuing multiple tasks or a single large task, the tasks will get randomly restarted and fail after the configured amount of retries. This happens regardless of the `runInForeground` setting.

I'd be glad to provide any additional logs. The cancellation doesn't mention any details and debugging on "all exceptions" doesn't stop for this one. I'm not sure how I might go about gathering additional info about the reason for cancelling the task.

**Logs**
Just a fragment, it looks the same for all tasks. Not sure why `Stopping foreground service` is logged only once.
Also, the `Moving WorkSpec to the foreground` is logged a bunch of times for the same taskId. Not sure if that's intentional.
```
I/WM-Processor(28372): Moving WorkSpec (3e2b0a26-1f15-49a3-9d51-35c344bce552) to the foreground
I/WM-Processor(28372): Moving WorkSpec (5bae0f37-2493-485e-9d06-f83526377023) to the foreground
I/WM-SystemFgDispatcher(28372): Stopping foreground service
I/WM-WorkerWrapper(28372): Work [ id=5bae0f37-2493-485e-9d06-f83526377023, tags={ com.bbflight.background_downloader.UploadTaskWorker, BackgroundDownloader, taskId=f876e9fc-8182-434f-ae9e-1e00cac24fcf, group=upload } ] was cancelled
I/WM-WorkerWrapper(28372): java.util.concurrent.CancellationException: Task was cancelled.
I/WM-WorkerWrapper(28372): 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1183)
I/WM-WorkerWrapper(28372): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:513)
I/WM-WorkerWrapper(28372): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
I/WM-WorkerWrapper(28372): 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:316)
I/WM-WorkerWrapper(28372): 	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
I/WM-WorkerWrapper(28372): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
I/WM-WorkerWrapper(28372): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
I/WM-WorkerWrapper(28372): 	at java.lang.Thread.run(Thread.java:1012)
I/WM-WorkerWrapper(28372): Work [ id=25d12f7d-a9f3-46fe-82e5-99d4fe6622e9, tags={ com.bbflight.background_downloader.UploadTaskWorker, BackgroundDownloader, taskId=33716db6-a5f6-49af-a94c-8749126bd376, group=upload } ] was cancelled
I/WM-WorkerWrapper(28372): java.util.concurrent.CancellationException: Task was cancelled.
I/WM-WorkerWrapper(28372): 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1183)
I/WM-WorkerWrapper(28372): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:513)
I/WM-WorkerWrapper(28372): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
I/WM-WorkerWrapper(28372): 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:316)
I/WM-WorkerWrapper(28372): 	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
I/WM-WorkerWrapper(28372): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
I/WM-WorkerWrapper(28372): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
I/WM-WorkerWrapper(28372): 	at java.lang.Thread.run(Thread.java:1012)
I/WM-WorkerWrapper(28372): Work [ id=44ec5e01-5d34-4a0d-8da0-0628ae7f88d2, tags={ com.bbflight.background_downloader.UploadTaskWorker, BackgroundDownloader, taskId=ed27beed-684c-4351-a588-96dda2f0bdef, group=upload } ] was cancelled
I/WM-WorkerWrapper(28372): java.util.concurrent.CancellationException: Task was cancelled.
I/WM-WorkerWrapper(28372): 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1183)
I/WM-WorkerWrapper(28372): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:513)
I/WM-WorkerWrapper(28372): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
I/WM-WorkerWrapper(28372): 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:316)
I/WM-WorkerWrapper(28372): 	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
I/WM-WorkerWrapper(28372): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
I/WM-WorkerWrapper(28372): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
I/WM-WorkerWrapper(28372): 	at java.lang.Thread.run(Thread.java:1012)
I/WM-WorkerWrapper(28372): Work [ id=3e2b0a26-1f15-49a3-9d51-35c344bce552, tags={ com.bbflight.background_downloader.UploadTaskWorker, BackgroundDownloader, taskId=3689d682-ddc6-49aa-b901-a6f9e1de4e9e, group=upload } ] was cancelled
I/WM-WorkerWrapper(28372): java.util.concurrent.CancellationException: Task was cancelled.
I/WM-WorkerWrapper(28372): 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1183)
I/WM-WorkerWrapper(28372): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:513)
I/WM-WorkerWrapper(28372): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
I/WM-WorkerWrapper(28372): 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:316)
I/WM-WorkerWrapper(28372): 	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
I/WM-WorkerWrapper(28372): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
I/WM-WorkerWrapper(28372): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
I/WM-WorkerWrapper(28372): 	at java.lang.Thread.run(Thread.java:1012)
D/ConnectivityManager(28372): StackLog: [android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:4863)] [androidx.work.impl.utils.NetworkApi21.unregisterNetworkCallbackCompat(NetworkApi21.kt:31)] [androidx.work.impl.constraints.trackers.NetworkStateTracker24.stopTracking(NetworkStateTracker.kt:153)] [androidx.work.impl.constraints.trackers.ConstraintTracker.removeListener(ConstraintTracker.kt:72)] [androidx.work.impl.constraints.controllers.ConstraintController$track$1$1.invoke(ContraintControllers.kt:56)] [androidx.work.impl.constraints.controllers.ConstraintController$track$1$1.invoke(ContraintControllers.kt:55)] [kotlinx.coroutines.channels.ProduceKt.awaitClose(Produce.kt:54)] [kotlinx.coroutines.channels.ProduceKt$awaitClose$1.invokeSuspend(Unknown Source:13)] [kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)] [kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)] [androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)] [java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)] [java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)] [java.lang.Thread.run(Thread.java:1012)]
D/ConnectivityManager(28372): StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4191)] [android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:4755)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4722)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4696)] [androidx.work.impl.utils.NetworkApi24.registerDefaultNetworkCallbackCompat(NetworkApi24.kt:28)] [androidx.work.impl.constraints.trackers.NetworkStateTracker24.startTracking(NetworkStateTracker.kt:138)] [androidx.work.impl.constraints.trackers.ConstraintTracker.addListener(ConstraintTracker.kt:56)] [androidx.work.impl.constraints.controllers.ConstraintController$track$1.invokeSuspend(ContraintControllers.kt:54)] [androidx.work.impl.constraints.controllers.ConstraintController$track$1.invoke(Unknown Source:8)] [androidx.work.impl.constraints.controllers.ConstraintController$track$1.invoke(Unknown Source:4)] [kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo$suspendImpl(Builders.kt:320)] [kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo(Unknown Source:0)] [kotlinx.coroutines.flow.CallbackFlowBuilder.collectTo(Builders.kt:334)] [kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)] [kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)] [kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)] [androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)] [java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)] [java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)] [java.lang.Thread.run(Thread.java:1012)]
I/TaskWorker(28372): Canceled task with id 33716db6-a5f6-49af-a94c-8749126bd376: Job was cancelled
```

**Code**
```dart
    FileDownloader().configure(
      globalConfig: (Config.holdingQueue, (5, null, null)),
      androidConfig: (
        Config.runInForeground,
        Config.always
      ),
    );

    FileDownloader().configureNotification(
      running:
          const TaskNotification('Uploading', 'file: {filename}'),
      progressBar: true,
    );

// ...

        final enqueueSuccess = await _uploader.enqueue(
          downloader.UploadTask(
            url: Uri.encodeFull(EnvConfig.WEBDAV_URL + candidate.remotePath!),
            requiresWiFi: false,
            baseDirectory: downloader.BaseDirectory.root,
            directory: dirname(candidate.path),
            filename: basename(candidate.path),
            httpRequestMethod: 'PUT',
            group: 'upload',
            taskId: taskId,
            updates: downloader.Updates.statusAndProgress,
            post: 'binary',
            metaData: candidate.id.toString(),
            retries: 3,
            priority: candidate.priority,
          ),
        );
```

**Comment by 781flyingdutchman** [comment]
Two possible reasons:
1. Upload is canceled by server (because it takes too long or is too slow)
2. Upload is canceled by Android OS (especially on less-performant devices the Android OEM often implements aggressive background task management to improve perceived performance, and this includes unceremoniously canceling background tasks)

The second is most likely given how you describe the problem, and unfortunately there is nothing you can do about that.  There is nothing in the logs that stands out.

**Comment by Ansis100** [comment]
>     1. Upload is canceled by server (because it takes too long or is too slow)

Don't think so. The DAV logs show errors mentioning incomplete downloads (i.e. `expected x bytes, received y bytes`), which probably means the client is terminating the connection too soon.

Does this mean that big file on slow devices are generally impossible to upload? Could this be solved by switching to the `MemoryQueue`?

If nothing can be done about this then we might need to think about chunking these kinds of slow uploads.

**Comment by 781flyingdutchman** [comment]
Since you mentioned a slow Android 12 device I think it's likely that the OS cancels the task because it is trying to manage performance. If you Google around you'll see lots of examples of that, and there is nothing you can do except indeed chunking the upload.

**Comment by Ansis100** [comment]
Alright, I'll look into that. Thanks for the info!
